# Generated by Django 5.1.5 on 2025-01-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_parent_remove_item_category_item_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
