# Generated by Django 5.1.5 on 2025-01-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_item_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='WornItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worn_logs', to='myapp.item')),
            ],
        ),
    ]
